/**
 * REPORT CONTROLLER
 * 
 * This file handles the generation of summarized analytics.
 * It uses MongoDB aggregation pipelines to calculate average lifestyle 
 * metrics and productivity scores over specific time windows (e.g., 7 days).
 */

const DailyLog = require('../models/DailyLog');
const Prediction = require('../models/Prediction');
const mongoose = require('mongoose');

/**
 * GET WEEKLY SUMMARY
 * GET /api/reports/summary
 * 
 * Aggregates various metrics from the last 7 days to provide a "Macro View" 
 * of the user's performance.
 */
const getWeeklySummary = async (req, res, next) => {
  try {
    const sevenDaysAgo = new Date();
    sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);

    // Convert string ID to a MongoDB ObjectId for the aggregation engine
    const userId = new mongoose.Types.ObjectId(req.user.id);

    /**
     * 1. AGGREGATION: DailyLog Averages
     * We group all logs from the last 7 days and calculate the mean for each metric.
     */
    const logAverages = await DailyLog.aggregate([
      { $match: { userId: userId, date: { $gte: sevenDaysAgo } } },
      {
        $group: {
          _id: null,
          avgSleepHours: { $avg: "$sleepHours" },
          avgStudyHours: { $avg: "$studyHours" },
          avgExerciseMins: { $avg: "$exerciseMins" },
          avgMoodScore: { $avg: "$moodScore" },
          avgStressLevel: { $avg: "$stressLevel" }
        }
      }
    ]);

    /**
     * 2. AGGREGATION: Prediction Averages
     * Calculates the average productivity score generated by the ML model.
     */
    const predictionAverages = await Prediction.aggregate([
      { $match: { userId: userId, date: { $gte: sevenDaysAgo } } },
      {
        $group: {
          _id: null,
          avgProductivityScore: { $avg: "$productivityScore" }
        }
      }
    ]);

    /**
     * 3. TREND DATA
     * Fetches a simple list of daily scores to render the "Trend Line" on the chart.
     */
    const trends = await Prediction.find({
      userId: userId,
      date: { $gte: sevenDaysAgo }
    }).sort({ date: 1 }).select('date productivityScore burnoutRisk');

    res.status(200).json({
      success: true,
      data: {
        averages: {
          // Merge the averages from both collections (DailyLog and Prediction)
          ...(logAverages[0] || {}),
          avgProductivityScore: predictionAverages[0]?.avgProductivityScore || 0
        },
        trends
      }
    });

  } catch (error) {
    next(error);
  }
};

module.exports = { getWeeklySummary };

